### ISSUE TITLE
[WoTLKC] Bugs after last game patch

### ISSUE THREAD

**Issue by Iowerth** [fusionpit/QuestFrameFixer#1]
Hi. Addon version is 2.0.
After yesterday's game patch there are many errors in BugSack.

```lua
1x QuestFrameFixer/QuestFrameFixer.lua:7: 'for' limit must be a number
[string "@QuestFrameFixer/QuestFrameFixer.lua"]:7: in function `getLineAndIconMaps'
[string "@QuestFrameFixer/QuestFrameFixer.lua"]:33: in main chunk

Locals:
maxLines = nil
titleIdent = "GossipTitleButton"
iconIdent = "GossipIcon"
lines = <table> {
}
icons = <table> {
}
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
```

```lua
1x QuestFrameFixer/QuestFrameFixer.lua:1 (null)

1x Interface_Wrath\FrameXML\Bindings.xml:1 QuestFrameFixer/QuestFrameFixer.lua:1 (null)
```

**Comment by fusionpit** [comment]
Blizzard introduced a refactor of the gossip system from Dragonflight into WotLK classic in the Ulduar patch. This addon has been updated in version 2.1-wrath to support the changes brought forth from that refactor.

You can get the latest version from the main sites, https://www.wowinterface.com/downloads/info25022-QuestFrameFixer.html or https://www.curseforge.com/wow/addons/questframefixer
